[package]
name = "adivinanzas"
version = "0.1.0"
edition = "2021"
authors = ["Atienza <rosaatienza@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.3.0"
